### ISSUE TITLE
Link to blog post is out of date

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/react-presentation-components#15]
This article is cited in several lessons:
https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0

However the author has added a 2019 caveat, which concludes as follows:
"This text is left intact for historical reasons but don’t take it too seriously."

Thank you.

**Comment by maxwellbenton** [comment]
Hi @ValerieHMoore,

Thank you for providing this feedback. We've added an addendum to this lesson and the later container component lesson noting this. We plan on adding content for hooks in a future update, but feel that the use of presentational/container components is still helpful for students learning how to structure their React apps, and will likely continue to include this content. The note should, however, prevent confusion caused by the note from Dan.

Thank you for contributing!
